# This workflow will install dependencies, install becquerel and run tests.
# It runs on multiple python3 versions on macOS, Ubuntu and Windows.
# It runs when a commit (merge) is push to the main (default) branch or for updates to a PR targeting main.
# Based on: https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml

name: tests

on:

  # When to test
  push:
    branches: [ $default-branch ]
  pull_request:
  workflow_dispatch:
  schedule:
    # 0700 UTC every day
    - cron: '00 7 * * *'

jobs:
  pip_build_test:

    # OS and python combos to test
    # Ubuntu 20.04 is specified because GHA are currently transitioning from
    # 18.04 to 20.04 and the `latest` tag could run on either.
    strategy:
      matrix:
        os: [ 'macos-latest', 'ubuntu-20.04', 'windows-latest' ]
        python-version: ['3.6', '3.7', '3.8', '3.9']
    runs-on: ${{ matrix.os }}

    # Installation and testing
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run pre-commit
        run: |
          pip install pre-commit
          pre-commit install
          pre-commit run --all-files --show-diff-on-failure
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --only-binary=numpy,scipy numpy scipy
          pip install -r requirements-dev.txt
      - name: Install package
        run: |
          pip install .
      - name: Test with pytest
        run: |
          python -c 'import becquerel;'
          pytest
